trigger:
- ms-iot

jobs:
  - job: Build67
    displayName: Build iMX 6 & 7
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        ClSomImx7_iMX7D_1GB:
          Target: ClSomImx7_iMX7D_1GB
        HummingBoardEdge_iMX6DL_1GB:
          Target: HummingBoardEdge_iMX6DL_1GB
        HummingBoardEdge_iMX6Q_2GB:
          Target: HummingBoardEdge_iMX6Q_2GB
        HummingBoardEdge_iMX6S_512MB:
          Target: HummingBoardEdge_iMX6S_512MB
        Sabre_iMX6Q_1GB:
          Target: Sabre_iMX6Q_1GB
        Sabre_iMX6QP_1GB:
          Target: Sabre_iMX6QP_1GB
        Sabre_iMX7D_1GB:
          Target: Sabre_iMX7D_1GB
        SabreLite_iMX6Q_1GB:
          Target: SabreLite_iMX6Q_1GB
        UdooNeo_iMX6SX_1GB:
          Target: UdooNeo_iMX6SX_1GB
        VAB820_iMX6Q_1GB:
          Target: VAB820_iMX6Q_1GB

    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install build-essential python python-dev python-crypto python-wand device-tree-compiler bison flex swig iasl uuid-dev wget git bc libssl-dev python3-pyelftools
      displayName: Download tools

    - script: |
        wget https://releases.linaro.org/components/toolchain/binaries/6.4-2017.11/arm-linux-gnueabihf/gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
        tar xf gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
      displayName: Download gcc

    # This must be run prior to cloning the other repos, otherwise it will find the imx-iotcore cgmanifest.json file and detect too many repos
    - task: ComponentGovernanceComponentDetection@0

    - script: |
        pushd ..
        git clone https://github.com/ms-iot/imx-iotcore.git
        popd
      displayName: Clone repos

    - script: |
        cp -r . ../optee_os
      displayName: Relocate optee directory

    - script: |
        pushd ../imx-iotcore
        echo build/firmware/$(Target)
        ls
        cd build/firmware/$(Target)
        make optee CROSS_COMPILE=$(Build.SourcesDirectory)/gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
      displayName: Build OP-TEE
